/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.echo.clientserver.sayhello.server;

import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author R
 */
public class Home extends javax.swing.JPanel {

    public Dashboard akses_dash;
    Registry registry;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_alas = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_diskonek = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_konek = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        panel_alas.setBackground(new java.awt.Color(245, 245, 245));
        panel_alas.setLayout(null);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/echo/clientserver/sayhello/server/icon/Gambar_Dis.png"))); // NOI18N
        panel_alas.add(jLabel12);
        jLabel12.setBounds(610, 180, 110, 120);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Disconnect");
        panel_alas.add(jLabel13);
        jLabel13.setBounds(600, 310, 130, 29);

        btn_diskonek.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn_diskonek.setForeground(new java.awt.Color(255, 255, 255));
        btn_diskonek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_diskonek.setText("Disconnect");
        btn_diskonek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_diskonek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_diskonekMouseClicked(evt);
            }
        });
        panel_alas.add(btn_diskonek);
        btn_diskonek.setBounds(585, 365, 170, 35);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/echo/clientserver/sayhello/server/icon/Button_Dis.png"))); // NOI18N
        panel_alas.add(jLabel14);
        jLabel14.setBounds(580, 360, 176, 50);

        btn_konek.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn_konek.setForeground(new java.awt.Color(255, 255, 255));
        btn_konek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_konek.setText("Connect");
        btn_konek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_konek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_konekMouseClicked(evt);
            }
        });
        panel_alas.add(btn_konek);
        btn_konek.setBounds(185, 375, 160, 35);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/echo/clientserver/sayhello/server/icon/Button_Connect.png"))); // NOI18N
        panel_alas.add(jLabel8);
        jLabel8.setBounds(180, 370, 176, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/echo/clientserver/sayhello/server/icon/Gambar_Connect.png"))); // NOI18N
        panel_alas.add(jLabel9);
        jLabel9.setBounds(210, 190, 110, 120);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setText("WORK");
        panel_alas.add(jLabel11);
        jLabel11.setBounds(230, 320, 80, 29);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/echo/clientserver/sayhello/server/icon/Dasar_Connect.png"))); // NOI18N
        panel_alas.add(jLabel6);
        jLabel6.setBounds(125, 175, 273, 278);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/echo/clientserver/sayhello/server/icon/Dasar_Dis.png"))); // NOI18N
        panel_alas.add(jLabel7);
        jLabel7.setBounds(530, 170, 273, 278);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_alas, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_alas, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_diskonekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_diskonekMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            gak_bisa();
        } catch (RemoteException ex) {
            Logger.getLogger(login_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_diskonekMouseClicked

    private void btn_konekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_konekMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            bisa();
            ubah_status_online();
        } catch (RemoteException ex) {
            Logger.getLogger(login_form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_konekMouseClicked

    public void ubah_status_online(){
//        akses_dash.txt_status.setText("Online");
        
    }
    
    private void bisa() throws RemoteException{
        registry = LocateRegistry.createRegistry(1098);
        
        SayHelloServer sayHello = new SayHelloServer();
        registry.rebind("sayHello", sayHello);
        
        System.out.println("Server Terhubung");
        
    }
    
    private void gak_bisa() throws RemoteException{
        registry = null;
        
        SayHelloServer sayHello = new SayHelloServer();
        
        System.out.println("Server Putus");
       
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_diskonek;
    private javax.swing.JLabel btn_konek;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panel_alas;
    // End of variables declaration//GEN-END:variables
}
