/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wordpress.yyaayyaatt.JIFrame.report;

import com.wordpress.yyaayyaatt.dialog.BrowseMahasiswa;
import com.wordpress.yyaayyaatt.model.Mahasiswa;
import krs.KRS;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author agoes
 */
public class JIFKRSReport extends javax.swing.JInternalFrame {

    private Mahasiswa mahasiswa;

    /**
     * Creates new form JIFSiswaReport
     */
    public JIFKRSReport() {

        initComponents();
        txtNim.setVisible(false);
        txtNama.setVisible(false);
        btnBrowse.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new com.apotik.widget.Panel();
        jPanel1 = new javax.swing.JPanel();
        btnBrowse = new javax.swing.JButton();
        txtNim = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rBtnALl = new javax.swing.JRadioButton();
        rBtnByNim = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlReport = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        jPanel1.setOpaque(false);

        btnBrowse.setText("...");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        txtNim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNimKeyPressed(evt);
            }
        });

        txtNama.setEditable(false);
        txtNama.setBackground(new java.awt.Color(255, 255, 204));
        txtNama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNama.setText("nama mahasiswa");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pilihan :");

        buttonGroup1.add(rBtnALl);
        rBtnALl.setForeground(new java.awt.Color(255, 255, 255));
        rBtnALl.setSelected(true);
        rBtnALl.setText("Semua Mahasiswa");
        rBtnALl.setOpaque(false);
        rBtnALl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rBtnALlItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rBtnByNim);
        rBtnByNim.setForeground(new java.awt.Color(255, 255, 255));
        rBtnByNim.setText("By NIM");
        rBtnByNim.setOpaque(false);
        rBtnByNim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rBtnByNimItemStateChanged(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mahasiswa :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rBtnALl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rBtnByNim))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBrowse)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rBtnALl)
                    .addComponent(rBtnByNim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Report Preview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        pnlReport.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlReport.setOpaque(false);
        pnlReport.setLayout(new java.awt.BorderLayout());
        jPanel2.add(pnlReport, java.awt.BorderLayout.CENTER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wordpress/yyaayyaatt/gui/resource/images/contents.png"))); // NOI18N
        jButton1.setText("Prewiew");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JasperPrint print = null;
        if(rBtnByNim.isSelected()){
        print = KRS.getkRSReportService().getKRSByNim(txtNim.getText());
        }else if(rBtnALl.isSelected()){
        print = KRS.getkRSReportService().getKRSAll();
        }
        System.err.println("print = " + print);
        JRViewer viewer = new JRViewer(print);

        pnlReport.removeAll();
        pnlReport.add(viewer);
        pnlReport.updateUI();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        if (txtNim.getText().isEmpty()) {
            mahasiswa = new BrowseMahasiswa().getMahasiswa();
            if (mahasiswa != null) {
                mahasiswa = KRS.getMahasiswaService().getMahasiswa(mahasiswa.getId());
                txtNim.setText(String.valueOf(mahasiswa.getNim()));
                txtNama.setText(mahasiswa.getNama());

                jButton1.requestFocusInWindow();
                jButton1ActionPerformed(evt);
            }
        } else {
            mahasiswa = KRS.getMahasiswaService().getMahasiswa(mahasiswa.getId());
            txtNim.setText(String.valueOf(mahasiswa.getNim()));
            txtNama.setText(mahasiswa.getNama());

            jButton1.requestFocusInWindow();
            jButton1ActionPerformed(evt);

        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void txtNimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNimKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNimKeyPressed

    private void rBtnALlItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rBtnALlItemStateChanged
        // TODO add your handling code here:
        if (rBtnALl.isSelected()) {
            txtNim.setVisible(false);
            txtNama.setVisible(false);
            btnBrowse.setVisible(false);
        }
    }//GEN-LAST:event_rBtnALlItemStateChanged

    private void rBtnByNimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rBtnByNimItemStateChanged
        // TODO add your handling code here:
        if (rBtnByNim.isSelected()) {
            txtNim.setVisible(true);
            txtNama.setVisible(true);
            btnBrowse.setVisible(true);
            txtNim.requestFocusInWindow();
        }
    }//GEN-LAST:event_rBtnByNimItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.apotik.widget.Panel panel1;
    private javax.swing.JPanel pnlReport;
    private javax.swing.JRadioButton rBtnALl;
    private javax.swing.JRadioButton rBtnByNim;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    // End of variables declaration//GEN-END:variables
}
