/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wordpress.yyaayyaatt.JIFrame.report;

import com.wordpress.yyaayyaatt.dialog.BrowseDosen;
import com.wordpress.yyaayyaatt.model.Dosen;
import krs.KRS;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author agoes
 */
public class JIFMKReport extends javax.swing.JInternalFrame {

    private Dosen dosen;

    /**
     * Creates new form JIFSiswaReport
     */
    public JIFMKReport() {

        initComponents();
        txtNim.setVisible(false);
        txtNama.setVisible(false);
        jButton2.setVisible(false);

        cmbTA.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new com.apotik.widget.Panel();
        jPanel2 = new javax.swing.JPanel();
        pnlReport = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbtnAll = new javax.swing.JRadioButton();
        rBtnByDosen = new javax.swing.JRadioButton();
        rBtnByTa = new javax.swing.JRadioButton();
        txtNim = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        cmbTA = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnPreview = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Laporan Mata Kuliah");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Report Preview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        pnlReport.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlReport.setOpaque(false);
        pnlReport.setLayout(new java.awt.BorderLayout());
        jPanel2.add(pnlReport, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pilihan :");

        buttonGroup1.add(rbtnAll);
        rbtnAll.setForeground(new java.awt.Color(102, 255, 102));
        rbtnAll.setSelected(true);
        rbtnAll.setText("Semua Data");
        rbtnAll.setOpaque(false);
        rbtnAll.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnAllItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rBtnByDosen);
        rBtnByDosen.setForeground(new java.awt.Color(255, 255, 204));
        rBtnByDosen.setText("By Dosen");
        rBtnByDosen.setOpaque(false);
        rBtnByDosen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rBtnByDosenItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rBtnByTa);
        rBtnByTa.setForeground(new java.awt.Color(204, 204, 255));
        rBtnByTa.setText("By Thn. Akademik");
        rBtnByTa.setOpaque(false);
        rBtnByTa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rBtnByTaItemStateChanged(evt);
            }
        });

        txtNim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNimKeyPressed(evt);
            }
        });

        txtNama.setEditable(false);
        txtNama.setBackground(new java.awt.Color(255, 255, 204));
        txtNama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNama.setText("nama");
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cmbTA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2012-2013", "2013-2014", "2014-2015" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mahasiswa :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnAll)
                        .addGap(2, 2, 2)
                        .addComponent(rBtnByTa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rBtnByDosen)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNim, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTA, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rBtnByTa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rBtnByDosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbtnAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNama)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(cmbTA, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNim)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btnPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wordpress/yyaayyaatt/gui/resource/images/contents.png"))); // NOI18N
        btnPreview.setText("Preview");
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (txtNim.getText().isEmpty()) {
            dosen = new BrowseDosen().getDosen();
            if (dosen != null) {
                dosen = KRS.getDosenService().getDosen(dosen.getId());
                txtNim.setText(String.valueOf(dosen.getKd_dosen()));
                txtNama.setText(dosen.getDosen());

                btnPreview.requestFocusInWindow();
            }
        } else {
            dosen = KRS.getDosenService().getDosen(dosen.getId());
            txtNim.setText(String.valueOf(dosen.getKd_dosen()));
            txtNama.setText(dosen.getDosen());

            btnPreview.requestFocusInWindow();

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNimKeyPressed
        // TODO add your handling code here:
        jButton2ActionPerformed(null);
    }//GEN-LAST:event_txtNimKeyPressed

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        // TODO add your handling code here:
        JasperPrint print = null;
        if (rbtnAll.isSelected()) {
            print = KRS.getkRSReportService().getMKAll();
        } else if (rBtnByDosen.isSelected()) {
            print = KRS.getkRSReportService().getMKByDosen(txtNim.getText());
        }else if (rBtnByTa.isSelected()) {
            print = KRS.getkRSReportService().getMKByTa(cmbTA.getSelectedItem().toString());
        }
        System.err.println("print = " + print);
        JRViewer viewer = new JRViewer(print);

        pnlReport.removeAll();
        pnlReport.add(viewer);
        pnlReport.updateUI();
    }//GEN-LAST:event_btnPreviewActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void rbtnAllItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnAllItemStateChanged
        // TODO add your handling code here:
        if (rbtnAll.isSelected()) {
            txtNim.setVisible(false);
            txtNama.setVisible(false);
            jButton2.setVisible(false);
            cmbTA.setVisible(false);
            txtNim.setText("");
            txtNama.setText("");
            btnPreview.requestFocusInWindow();
        }
    }//GEN-LAST:event_rbtnAllItemStateChanged

    private void rBtnByDosenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rBtnByDosenItemStateChanged
        // TODO add your handling code here:
        if (rBtnByDosen.isSelected()) {
            txtNim.setVisible(true);
            txtNama.setVisible(true);
            jButton2.setVisible(true);
            cmbTA.setVisible(false);
            txtNim.requestFocusInWindow();
        }
    }//GEN-LAST:event_rBtnByDosenItemStateChanged

    private void rBtnByTaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rBtnByTaItemStateChanged
        // TODO add your handling code here:
        if (rBtnByTa.isSelected()) {
            txtNim.setVisible(false);
            txtNama.setVisible(false);
            jButton2.setVisible(false);
            cmbTA.setVisible(true);
        }
    }//GEN-LAST:event_rBtnByTaItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPreview;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbTA;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.apotik.widget.Panel panel1;
    private javax.swing.JPanel pnlReport;
    private javax.swing.JRadioButton rBtnByDosen;
    private javax.swing.JRadioButton rBtnByTa;
    private javax.swing.JRadioButton rbtnAll;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    // End of variables declaration//GEN-END:variables
}
