/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.echo.clientserver.sayhello.client;

import com.echo.clientserver.sayhello.SayHello;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import sun.font.TextRecord;

/**
 *
 * @author R
 */
public class FormClient extends javax.swing.JFrame {

    private SayHello sayHello;
    /**
     * Creates new form FormClient
     */
    public FormClient() {
        
        try {
            sayHello = (SayHello)Naming.lookup("rmi://localhost:1099/sayHello");
        } catch(NotBoundException ex) {
            System.out.println("Terjadi Error Dengan Pesan:"+ex.getMessage());
            System.exit(1);
        } catch(MalformedURLException ex) {
            System.out.println("Terjadi Error Dengan Pesan:"+ex.getMessage());
            System.exit(1);
        } catch(RemoteException ex) {
            System.out.println("Terjadi Error Dengan Pesan:"+ex.getMessage());
            System.exit(1);
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nama = new javax.swing.JLabel();
        et_nama = new javax.swing.JTextField();
        btn_sayHello = new javax.swing.JButton();
        lbl_responServer = new javax.swing.JLabel();
        et_responServer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_nama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_nama.setText("Nama :");

        et_nama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_namaActionPerformed(evt);
            }
        });

        btn_sayHello.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_sayHello.setText("Say Hello");
        btn_sayHello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sayHelloActionPerformed(evt);
            }
        });

        lbl_responServer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_responServer.setText("Respon dari server:");

        et_responServer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_responServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_responServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_responServer)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(et_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_sayHello))
                    .addComponent(lbl_nama)
                    .addComponent(et_responServer))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbl_nama)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(et_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sayHello))
                .addGap(18, 18, 18)
                .addComponent(lbl_responServer)
                .addGap(18, 18, 18)
                .addComponent(et_responServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void et_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_namaActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_et_namaActionPerformed

    private void et_responServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_responServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_responServerActionPerformed

    private void btn_sayHelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sayHelloActionPerformed
        // TODO add your handling code here:
        try {
            String nama = et_nama.getText();
            String response = sayHello.sayHello(nama);
            et_responServer.setText(response);
        } catch (RemoteException ex) {
            System.err.println("Terjadi Error Dengan Pesan:"+ex.getMessage());
            System.exit(1);
        }
    }//GEN-LAST:event_btn_sayHelloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sayHello;
    private javax.swing.JTextField et_nama;
    private javax.swing.JTextField et_responServer;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_responServer;
    // End of variables declaration//GEN-END:variables
}
