/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InputDosen.java
 *
 * Created on Oct 19, 2010, 7:50:44 PM
 */
package com.wordpress.yyaayyaatt.JIFrame;

import com.wordpress.yyaayyaatt.model.Dosen;
import com.wordpress.yyaayyaatt.model.Pembimbing;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import krs.KRS;

/**
 *
 * @author bahrie
 */
public final class InputPembimbing extends javax.swing.JInternalFrame {

    List<Pembimbing> pembimbings = new ArrayList<Pembimbing>();
    List<Dosen> dosens = new ArrayList<Dosen>();
    Pembimbing pembimbing;
    Dosen dosen;
    int row;

    /**
     * Creates new form DataDosen
     */
    public InputPembimbing() {
        initComponents();
        this.statusAwal();
    }

    void kosongkanTeks() {
        txtKdPembimbing.setText("");
    }

    void isiListDosen() {
        cmbDosen.removeAllItems();
        dosens = krs.KRS.getDosenService().getAll();
        for (Dosen dsn : dosens) {
            cmbDosen.addItem(dsn.getDosen());
        }
    }

    void isiTeks() {
        Pembimbing pemb = pembimbings.get(row);
        txtKdPembimbing.setText(pemb.getKode_pembimbing());
        cmbDosen.setSelectedItem(pemb.getDosen());
    }

    void isiTabel() {
        try {
            pembimbings = KRS.getPembimbingService().getAll();
            Object[][] data = new Object[pembimbings.size()][4];

            int x = 0;
            for (Pembimbing pemb : pembimbings) {
                data[x][0] = pemb.getKode_pembimbing();
                data[x][1] = pemb.getDosen();

                x++;
            }
            String[] judul = {"Kode Pembimbing", "Nama"};
            tableDosen.setModel(new DefaultTableModel(data, judul));
            jScrollPane1.setViewportView(tableDosen);
        } catch (Throwable ex) {
            ex.printStackTrace();
        }
    }

    void statusAwal() {
        this.kosongkanTeks();
        this.isiListDosen();
        isiTabel();
        txtKdPembimbing.setEnabled(false);
        cmbDosen.setEnabled(false);
        btnEdit.setText("Edit");
        btnTambah.setText("Tambah");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new com.apotik.widget.Panel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDosen = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        resetBotton = new javax.swing.JButton();
        panelInput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKdPembimbing = new javax.swing.JTextField();
        cmbDosen = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pembimbing");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/report/logoPolForm.png"))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabel Pembimbing", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);

        tableDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDosenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDosen);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wordpress/yyaayyaatt/gui/resource/button/tambah.gif"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wordpress/yyaayyaatt/gui/resource/button/kurang.gif"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wordpress/yyaayyaatt/gui/resource/button/resep.gif"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        resetBotton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wordpress/yyaayyaatt/gui/resource/button/exit.gif"))); // NOI18N
        resetBotton.setText("Cancel");
        resetBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(resetBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit)
                    .addComponent(resetBotton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pembimbing", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        panelInput.setForeground(new java.awt.Color(255, 255, 255));
        panelInput.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Kode Pembimbing :");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama :");

        cmbDosen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKdPembimbing)
                    .addComponent(cmbDosen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKdPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if (btnTambah.getText().equals("Tambah")) {

            txtKdPembimbing.setEnabled(true);
            cmbDosen.setEnabled(true);
            btnTambah.setText("Simpan");
            txtKdPembimbing.requestFocusInWindow();
        } else {
            if (txtKdPembimbing.getText().isEmpty()) {
                JOptionPane.showMessageDialog(InputPembimbing.this, "Isi Semua Data!!", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
            } else {
                String kode=null,nama=null;
                List<Pembimbing>p = KRS.getPembimbingService().getPembimbingByKode(txtKdPembimbing.getText());
                for (Pembimbing p1 : p) {
                    kode = p1.getKode_pembimbing();
                    nama = p1.getDosen();
                }
                if (kode==null && nama ==null) {
                SimpanData();
                statusAwal();
                }else{
                    JOptionPane.showConfirmDialog(InputPembimbing.this, "Kode dan Dosen sudah terdaftar","Peringatan",JOptionPane.ERROR_MESSAGE);
                    
                }
            }
        }
}//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed

        if (pembimbing != null) {
            KRS.getPembimbingService().delete(pembimbing);
            statusAwal();
            JOptionPane.showMessageDialog(this, "Berhasil");
            kosongkanTeks();
            statusAwal();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal!!!");
//            }
        }
}//GEN-LAST:event_btnHapusActionPerformed
    void Enabled(Boolean b) {
        txtKdPembimbing.setEnabled(b);
        cmbDosen.setEnabled(b);
    }
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (btnEdit.getText().equals("Edit")) {
            btnEdit.setText("Simpan");
            btnHapus.setEnabled(false);
            Enabled(true);
            txtKdPembimbing.requestFocusInWindow();
        } else if (btnEdit.getText().equals("Simpan")) {
            saveOrUpdateData();
            statusAwal();
        }
    }//GEN-LAST:event_btnEditActionPerformed
    void saveOrUpdateData() {
        if (pembimbing == null) {
            pembimbing = new Pembimbing();
        }
        System.out.println("pembimbing = " + pembimbing);
        pembimbing.setKode_pembimbing(txtKdPembimbing.getText());
        pembimbing.setDosen(cmbDosen.getSelectedItem().toString());
        KRS.getPembimbingService().insert(pembimbing);
        this.statusAwal();
    }
    private void resetBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBottonActionPerformed
        // TODO add your handling code here:
        this.statusAwal();
        btnTambah.setEnabled(true);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
}//GEN-LAST:event_resetBottonActionPerformed

    private void tableDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDosenMouseClicked
        // TODO add your handling code here:
        klikTable();
        btnTambah.setEnabled(false);
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
    }//GEN-LAST:event_tableDosenMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox cmbDosen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.apotik.widget.Panel panel1;
    private javax.swing.JPanel panelInput;
    private javax.swing.JButton resetBotton;
    private javax.swing.JTable tableDosen;
    private javax.swing.JTextField txtKdPembimbing;
    // End of variables declaration//GEN-END:variables
void SimpanData() {
        if (pembimbing == null) {
            pembimbing = new Pembimbing();
        }
        pembimbing.setKode_pembimbing(txtKdPembimbing.getText());
        pembimbing.setDosen(cmbDosen.getSelectedItem().toString());
        KRS.getPembimbingService().insert(pembimbing);
        this.statusAwal();

        pembimbing = new Pembimbing();
        JOptionPane.showMessageDialog(null, "Simpan Sukses", "Konfirmasi", JOptionPane.INFORMATION_MESSAGE);
    }

    void klikTable() {
        if (tableDosen.getSelectedRow() >= 0) {
            pembimbing = pembimbings.get(tableDosen.getSelectedRow());
            pembimbing = KRS.getPembimbingService().getID(pembimbing.getId());
            System.out.print("mahasiswa = " + pembimbing);
            loadModelToForm();
        }
    }

    private void loadModelToForm() {
        txtKdPembimbing.setText(pembimbing.getKode_pembimbing());
        cmbDosen.setSelectedItem(pembimbing.getDosen());
    }
}
