/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wordpress.yyaayyaatt.JIFrame;

import com.wordpress.yyaayyaatt.dialog.BrowseMk;
import com.wordpress.yyaayyaatt.model.DetailKrs;
import com.wordpress.yyaayyaatt.model.Kelas;
import com.wordpress.yyaayyaatt.model.Mahasiswa;
import com.wordpress.yyaayyaatt.model.Mk;
import com.wordpress.yyaayyaatt.model.WaktuKrs;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import krs.KRS;

/**
 *
 * @author Mr.Blue
 */
public class MahasiswaJIFrame extends javax.swing.JInternalFrame {

    private Mahasiswa mahasiswa;
    private Mk mk;
    List<Mahasiswa> mahasiswas = new ArrayList<Mahasiswa>();
    private Kelas kelases = new Kelas();
    private List<Mk> mks = new ArrayList<Mk>();
    private List<Mk> mks1 = new ArrayList<Mk>();
    private List<WaktuKrs> waktuKrses = new ArrayList<WaktuKrs>();
    private List<Mk> mks2 = new ArrayList<Mk>();
    private List<DetailKrs> detailKrses = new ArrayList<DetailKrs>();
    int mahasiswa1;
    WaktuKrs waktuKrs;
    DetailKrs detailKrs;

    /**
     * Creates new form MahasiswaJIFrame
     */
    public MahasiswaJIFrame(int mahasiswa) {
        initComponents();

        this.mahasiswa1 = mahasiswa;
        System.err.println("mahasiswa = " + mahasiswa1);
        if (mahasiswa1 != 0) {
            dataMahasiswa();
            isiTabelMk();
            addDetail();

        }
    }

    void tableByAll(List<Mk> params) {
        Object[][] data = new Object[params.size()][5];
        int x = 0;
        for (Mk mk : params) {
            data[x][0] = mk.getKd_mk();
            data[x][1] = mk.getMk();
            data[x][2] = mk.getSks();
            data[x][3] = mk.getTakad();
            x++;
        }
        String[] judul = {"Kode", "Nama", "Sks", "T. Akademik"};
        tableAmbil.setModel(new DefaultTableModel(data, judul));
        jScrollPane1.setViewportView(tableAmbil);
    }

    void tableBySemester(String smtr) {
        detailKrses = KRS.getDetailKrsService().getDetailKrsBySemester(mahasiswa1, smtr);
        Object[][] data = new Object[detailKrses.size()][5];
        int x = 0;
        for (DetailKrs dk : detailKrses) {
            data[x][0] = dk.getMk().getKd_mk();
            data[x][1] = dk.getMk().getMk();
            data[x][2] = dk.getMk().getSks();
            data[x][3] = dk.getMk().getTakad();
            x++;
        }
        String[] judul = {"Kode Mk", "Mk", "Sks", "Thn Akademik"};
        tableAmbil.setModel(new DefaultTableModel(data, judul));
        jScrollPane1.setViewportView(tableAmbil);
    }

    void isiTabelMk() {
        try {
            detailKrses = KRS.getDetailKrsService().getDetailKrsById(mahasiswa1);
            Object[][] data = new Object[detailKrses.size()][5];
            int x = 0;
            for (DetailKrs dk : detailKrses) {
                data[x][0] = dk.getMk().getKd_mk();
                data[x][1] = dk.getMk().getMk();
                data[x][2] = dk.getMk().getSks();
                data[x][3] = dk.getMk().getTakad();
                x++;
            }
            String[] judul = {"Kode Mk", "Mk", "Sks", "Thn Akademik"};
            tableAmbil.setModel(new DefaultTableModel(data, judul));
            jScrollPane1.setViewportView(tableAmbil);
        } catch (Throwable ex) {
            ex.printStackTrace();
        }
    }

    void addDetail() {
        for (DetailKrs s : detailKrses) {
            Mk mk = new Mk();
            mk.setId(s.getMk().getId());
            mk.setKd_mk(s.getMk().getKd_mk());
            mk.setMk(s.getMk().getMk());
            mk.setSks(s.getMk().getSks());
            mk.setTakad(s.getMk().getTakad());

            mks1.add(mk);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tableAmbil = new com.apotik.widget.Table();
        panel1 = new com.apotik.widget.Panel();
        panelKrs = new javax.swing.JPanel();
        jScrollPane1 = new com.apotik.widget.ScrollPane();
        panelMhs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNim = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        txtJumlahKrs = new javax.swing.JLabel();
        txtTa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlImage = new org.tm.container.JPanelImage();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rBtnAmbil = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rBtnLihat = new javax.swing.JRadioButton();
        cmbSmtr = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        tableAmbil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        setClosable(true);
        setMaximizable(true);
        setTitle("Pengambilan KRS Mahasiswa");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/report/logoPolForm.png"))); // NOI18N

        panelKrs.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabel Mata Kuliah", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        panelKrs.setOpaque(false);

        javax.swing.GroupLayout panelKrsLayout = new javax.swing.GroupLayout(panelKrs);
        panelKrs.setLayout(panelKrsLayout);
        panelKrsLayout.setHorizontalGroup(
            panelKrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKrsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelKrsLayout.setVerticalGroup(
            panelKrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKrsLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelMhs.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mahasiswa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        panelMhs.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nim");

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total KRS");

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tahun Ajaran");

        txtNim.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtNim.setForeground(new java.awt.Color(255, 255, 255));
        txtNim.setText("Nim :");

        txtNama.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setText("Nim :");

        txtJumlahKrs.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtJumlahKrs.setForeground(new java.awt.Color(255, 255, 255));
        txtJumlahKrs.setText("Nim :");

        txtTa.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtTa.setForeground(new java.awt.Color(255, 255, 255));
        txtTa.setText("Nim :");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        pnlImage.setPosition(1);

        javax.swing.GroupLayout pnlImageLayout = new javax.swing.GroupLayout(pnlImage);
        pnlImage.setLayout(pnlImageLayout);
        pnlImageLayout.setHorizontalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        pnlImageLayout.setVerticalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        jPanel2.add(pnlImage, java.awt.BorderLayout.CENTER);

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" : ");

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(" : ");

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(" : ");

        jLabel12.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(" : ");

        javax.swing.GroupLayout panelMhsLayout = new javax.swing.GroupLayout(panelMhs);
        panelMhs.setLayout(panelMhsLayout);
        panelMhsLayout.setHorizontalGroup(
            panelMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMhsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlahKrs, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(537, Short.MAX_VALUE))
        );
        panelMhsLayout.setVerticalGroup(
            panelMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMhsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNim)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtJumlahKrs)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTa)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelMhsLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setOpaque(false);

        buttonGroup1.add(rBtnAmbil);
        rBtnAmbil.setForeground(new java.awt.Color(255, 255, 255));
        rBtnAmbil.setText("Ambil KRS");
        rBtnAmbil.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Semester : ");

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Pilihan :");

        buttonGroup1.add(rBtnLihat);
        rBtnLihat.setForeground(new java.awt.Color(255, 255, 255));
        rBtnLihat.setSelected(true);
        rBtnLihat.setText("Lihat KRS");
        rBtnLihat.setOpaque(false);

        cmbSmtr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSmtr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<pilih semester>", "1", "2", "3", "4", "5", "6", "7", "8" }));
        cmbSmtr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbSmtr.setOpaque(false);
        cmbSmtr.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSmtrItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnLihat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBtnAmbil)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSmtr, 0, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSmtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(rBtnAmbil)
                    .addComponent(rBtnLihat)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setOpaque(false);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wordpress/yyaayyaatt/gui/resource/images/button_cancel.png"))); // NOI18N
        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wordpress/yyaayyaatt/gui/resource/images/ark2.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wordpress/yyaayyaatt/gui/resource/images/exit.png"))); // NOI18N
        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSimpan)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMhs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelKrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        simpanSks();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mks1.remove(tableAmbil.getSelectedRow());
        this.isitabelKrs();
        this.updateJmlhSks();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbSmtrItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSmtrItemStateChanged
        // TODO add your handling code here:
        if (rBtnLihat.isSelected()) {
            if (cmbSmtr.getSelectedItem().equals("All")) {
                isiTabelMk();
                this.updateJmlhSks();
            } else {
                tableBySemester(cmbSmtr.getSelectedItem().toString().trim());
                this.updateJmlhSks();
            }
        } else if (rBtnAmbil.isSelected()) {
            if (cmbSmtr.getSelectedItem().equals("1")) {
                mks1 = KRS.getMkService().getCari("TK1");
                tableByAll(mks1);
            } else if (cmbSmtr.getSelectedItem().equals("2")) {
                mks1 = KRS.getMkService().getCari("TK2");
                tableByAll(mks1);
            } else if (cmbSmtr.getSelectedItem().equals("3")) {
                mks1 = KRS.getMkService().getCari("TK3");
                tableByAll(mks1);
            } else if (cmbSmtr.getSelectedItem().equals("4")) {
                mks1 = KRS.getMkService().getCari("TK4");
                tableByAll(mks1);
            } else if (cmbSmtr.getSelectedItem().equals("5")) {
                mks1 = KRS.getMkService().getCari("TK5");
                tableByAll(mks1);
            } else if (cmbSmtr.getSelectedItem().equals("6")) {
                mks1 = KRS.getMkService().getCari("TK6");
                tableByAll(mks1);
            } else if (cmbSmtr.getSelectedItem().equals("7") || cmbSmtr.getSelectedItem().equals("8")) {
                tableBySemester(cmbSmtr.getSelectedItem().toString().trim());
                this.updateJmlhSks();
                paket();
            }
        }
    }//GEN-LAST:event_cmbSmtrItemStateChanged
    void paket() {
        mk = new BrowseMk().getMk();

        if (mk != null) {
            mk = KRS.getMkService().getID(mk.getId());
            int cadangan = mk.getSks();
            if (bolehTidak(mk)) {
                if ((Integer.valueOf(txtJumlahKrs.getText()) + cadangan) <= 24) {

                    mks1.add(mk);
                    this.isitabelKrs();
                    this.updateJmlhSks();
                    paket();
                } else {
                    JOptionPane.showMessageDialog(this, "SKS melebihi kuota", "Peringatan!", JOptionPane.ERROR_MESSAGE);
                    paket();
                }
            } else {
                JOptionPane.showMessageDialog(this, "mata kuliah sudah diambil", "Peringatan!", JOptionPane.ERROR_MESSAGE);
                paket();
            }

            jButton1.requestFocusInWindow();
        }
    }

    void isitabelKrs() {
        Object[][] data = new Object[mks1.size()][4];
        int x = 0;
        for (Mk mk : mks1) {
            data[x][0] = mk.getKd_mk();
            data[x][1] = mk.getMk();
            data[x][2] = mk.getSks();
            data[x][3] = mk.getTakad();
            x++;
        }
        String[] judul = {"Kode", "Nama", "Sks", "T. Akademik"};
        tableAmbil.setModel(new DefaultTableModel(data, judul));
        jScrollPane1.setViewportView(tableAmbil);
    }

    void updateJmlhSks() {
        int total = 0;
        for (Mk mk : mks1) {
            total = total + mk.getSks();
        }
        txtJumlahKrs.setText(String.valueOf(total));

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbSmtr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private com.apotik.widget.ScrollPane jScrollPane1;
    private com.apotik.widget.Panel panel1;
    private javax.swing.JPanel panelKrs;
    private javax.swing.JPanel panelMhs;
    private org.tm.container.JPanelImage pnlImage;
    private javax.swing.JRadioButton rBtnAmbil;
    private javax.swing.JRadioButton rBtnLihat;
    private com.apotik.widget.Table tableAmbil;
    private javax.swing.JLabel txtJumlahKrs;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtNim;
    private javax.swing.JLabel txtTa;
    // End of variables declaration//GEN-END:variables

    boolean bolehTidak(Mk mk) {
        boolean status = true;
        for (int a = 0; a < mks1.size(); a++) {
            if (mks1.get(a).getId() == mk.getId()) {
                status = false;
                break;
            } else {
                status = true;
            }
        }
        return status;
    }

    void dataMahasiswa() {
        waktuKrs = KRS.getWaktuKrsService().getID(1);
        mahasiswa = KRS.getMahasiswaService().getMahasiswa(mahasiswa1);
        txtJumlahKrs.setText(String.valueOf(mahasiswa.getJumlah_krs()));
        txtNama.setText(mahasiswa.getNama());
        txtNim.setText(mahasiswa.getNim());
        txtTa.setText(String.valueOf(mahasiswa.getThnmasuk()));
        String url = mahasiswa.getFoto();
        ImageIcon icon = new ImageIcon(url);
        pnlImage.setWallpaper(icon);
    }

    void simpanSks() {
        detailKrses = KRS.getDetailKrsService().getDetailKrsBySemester(mahasiswa.getId(), cmbSmtr.getSelectedItem().toString());
        for (DetailKrs d : detailKrses) {
            KRS.getDetailKrsService().delete(d);
            System.out.println("============================hapus=================================");
        }
        if (mks1 != null) {
            for (Mk mk : mks1) {
                Mk a = KRS.getMkService().getID(mk.getId());
                DetailKrs dt = new DetailKrs();
                dt.setWktu(new Date());
                dt.setMahasiswa(mahasiswa);
                dt.setSemester(cmbSmtr.getSelectedItem().toString());
                dt.setMk(a);

                KRS.getDetailKrsService().insert(dt);
            }
            mahasiswa.setJumlah_krs(Integer.parseInt(txtJumlahKrs.getText()));
            KRS.getMahasiswaService().insert(mahasiswa);
            JOptionPane.showMessageDialog(this, "Data sudah Tersimpan", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
            mks1 = new ArrayList<Mk>();
        } else {
            JOptionPane.showMessageDialog(this, "Tidak ada KRS baru yang diambil", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);

        }
    }
}
